name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6==6.7.0 Pillow==10.3.0 reportlab==4.2.0 pyinstaller==6.3.0
        pip install arabic-reshaper==3.0.0 python-bidi==0.4.2
        
    - name: List font files
      run: |
        echo "Font files found:"
        dir *.ttf
        
    - name: Build EXE with fonts and BiDi support
      run: |
        pyinstaller app.spec
        
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: ImageTools-Windows-WithPersianFix
        path: dist/ImageTools.exe
        retention-days: 30
