name: Build Windows EXE

on:
  push:
    branches: [ main ]
    paths: ['*.py']
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6==6.7.0 Pillow==10.3.0 reportlab==4.2.0 pyinstaller==6.3.0
        
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name=ImageTools --icon=icon.ico app.py
        
    - name: Test EXE (optional)
      run: |
        echo "EXE created successfully!"
        dir dist\
        
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: ImageTools-Windows-EXE
        path: dist/ImageTools.exe
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/ImageTools.exe
        body: |
          Windows executable for Image Tools application
          - Address Label Maker
          - Image Cropper (34mm x 34mm)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
